# Firebase Cloud Messaging (FCM)

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Messaging'
pod 'NabtoClient', '3.0.15'

target 'MessagingExample' do
end
target 'MessagingExampleSwift' do
end
target 'MessagingExampleTests' do
end
